server:
  port: 8075

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/GOTALENT
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      jdbc:
        lob:
         non_contextual_creational: true
